version: '3.7'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    image: php:8.2-fpm
    build: .
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - .:/var/www/app:delegated
  vite:
    image: node:20
    restart: unless-stopped
    working_dir: /var/www/app
    command: sh -c "npm install && npm run dev"
    volumes:
      - .:/var/www/app:delegated
    ports:
      - "5173:5173"
    depends_on:
      - php
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
