version: '3.7'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    image: php:8.2-fpm
    build: .
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - .:/var/www/app:delegated

networks:
  laravel:
    driver: bridge