version: '3.7'
services:
  php:
    image: php:8.2
    build: .
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - .:/var/www/app:delegated
    networks:
      - laravel
  vite:
    image: node:20
    restart: unless-stopped
    working_dir: /var/www/app
    command: /bin/sh -c "npm install && npm run build"
    volumes:
      - .:/var/www/app:delegated
    ports:
      - "5173:5173"
    depends_on:
      - php
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
